export const DEFAULT_GROUP_ALIASES: Record<string, string | string[]> = {
  gh: "github",
  git: "github",
  repo: "github",
  pr: "github",
  prs: "github",
  issues: "github",
  fs: ["filesystem_read", "filesystem_write"],
  files: ["filesystem_read", "filesystem_write"],
  file: "filesystem_read",
  read: "filesystem_read",
  write: "filesystem_write",
  cal: "calendar",
  calendar: "calendar",
  schedule: "calendar",
  events: "calendar",
  todo: "tasks",
  todos: "tasks",
  todoist: "tasks",
  task: "tasks",
  obs: "obs",
  stream: "obs",
  streaming: "obs",
  broadcast: "obs",
  wp: "wordpress",
  blog: "wordpress",
  weather: "weather",
  forecast: "weather",
  slack: "communication",
  discord: ["discord", "communication"],
  chat: "communication",
  message: "communication",
  whatsapp: "communication",
  email: "email",
  mail: "email",
  gmail: "email",
  drive: "drive",
  "google drive": "drive",
  docs: "drive",
  "google docs": "drive",
  document: "drive",
  documents: "drive",
  evernote: "evernote",
  note: "evernote",
  notes: "evernote",
  notebook: "evernote",
  dev: "development_tools",
  code: "development_tools",
  coding: "development_tools",
  research: "research",
  scrape: "research",
  crawl: "research",
  analytics: "analytics",
  stats: "analytics",
  toggl: "analytics",
  time: "analytics",
  support: ["freescout_read", "freescout_write"],
  ticket: "freescout_read",
  tickets: "freescout_read",
  freescout: ["freescout_read", "freescout_write"],
  memory: "memory",
  remember: "memory",
  recall: "memory",
  voice: "voice",
  tts: "voice",
  audio: "voice",
  elevenlabs: "voice",
  ios: "ios_app",
  "ios app": "ios_app",
  iphone: "ios_app",
  apns: "ios_app",
  mobile: "ios_app",
  "mobile app": "ios_app",
  "push notification": "ios_app",
  "push notifications": "ios_app",
  "live activity": "ios_app",
  "live activities": "ios_app"
};

export const DEFAULT_GROUP_SERVERS: Record<string, string[]> = {
  github: ["github"],
  github_read: ["github"],
  github_admin: ["github"],
  filesystem_read: ["desktop-commander"],
  filesystem_write: ["desktop-commander"],
  calendar: ["google_workspace"],
  tasks: ["todoist"],
  obs: ["obs"],
  wordpress: ["wordpress"],
  weather: ["weather"],
  communication: ["slack__T13EF1H4M", "slack__TP56GEBQR", "evernote", "google_workspace", "whatsapp"],
  slack: ["slack__T13EF1H4M", "slack__TP56GEBQR"],
  email: ["google_workspace"],
  evernote: ["evernote"],
  development_tools: ["context7", "desktop-commander"],
  research: ["bright-data"],
  analytics: ["mcp-toggl", "mcp-pirsch"],
  freescout_read: ["freescout"],
  freescout_write: ["freescout"],
  memory: ["memory"],
  voice: ["ElevenLabs"],
  search: ["bright-data"],
  drive: ["google_workspace"],
  ios_app: []
};
